In [37]:
import pandas as pd

In [38]:
churn_labels_db = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\churn_labels_db.csv")
customer_info_db = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db.csv")
usage_data_db = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\usage_data_db.csv")
customer_info_db2 = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db2.csv")
usage_data_db2 = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\usage_data_db2.csv")

In [39]:
churn_labels_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  10000 non-null  str
 1   Churn       10000 non-null  int64
dtypes: int64(1), str(1)
memory usage: 243.2 KB

In [40]:
churn_labels_db.describe()

              Churn
count  10000.000000
mean       0.078600
std        0.269127
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

In [41]:
churn_labels_db.duplicated().sum()

np.int64(0)

In [42]:
customer_info_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      10000 non-null  str
 1   Age             10000 non-null  float64
 2   Gender          10000 non-null  str
 3   Region          10000 non-null  str
 4   ContractType    10000 non-null  str
 5   MonthlyCharges  10000 non-null  float64
 6   SignupDate      10000 non-null  str
dtypes: float64(2), str(5)
memory usage: 905.5 KB

In [43]:
customer_info_db.describe()

                Age  MonthlyCharges
count  10000.000000    10000.000000
mean      43.364050       51.003994
std       12.097085       21.534495
min       18.000000        0.380000
25%       37.000000       39.797500
50%       43.000000       50.015000
75%       49.000000       60.500000
max       69.000000      390.300000

In [44]:
customer_info_db2.describe()

                age  monthly_charges
count  10000.000000     10000.000000
mean      43.364050        51.003994
std       12.097085        21.534495
min       18.000000         0.380000
25%       37.000000        39.797500
50%       43.000000        50.015000
75%       49.000000        60.500000
max       69.000000       390.300000

In [45]:
# Check for negative monthly charges
import pandas as pd

# Check for negative values in MonthlyCharges
negative_charges = customer_info_db[customer_info_db['MonthlyCharges'] < 0]
print(f"Number of customers with negative monthly charges: {len(negative_charges)}")

if len(negative_charges) > 0:
    print("\n" + "="*50)
    print("CUSTOMERS WITH NEGATIVE MONTHLY CHARGES")
    print("="*50)
    print(negative_charges)
    
    # Get statistics on monthly charges
    print("\n" + "="*50)
    print("MONTHLY CHARGES STATISTICS (BEFORE FIX)")
    print("="*50)
    print(customer_info_db['MonthlyCharges'].describe())
    
    # Fix negative values by converting to positive (sign error correction)
    print("\n" + "="*50)
    print("FIXING NEGATIVE VALUES")
    print("="*50)
    customer_info_db['MonthlyCharges'] = customer_info_db['MonthlyCharges'].abs()
    
    # Verify fix
    negative_after = customer_info_db[customer_info_db['MonthlyCharges'] < 0]
    print(f"Negative values after fix: {len(negative_after)}")
    
    # Show the corrected records
    corrected_customers = customer_info_db[customer_info_db['CustomerID'].isin(negative_charges['CustomerID'])]
    print("\nCorrected records:")
    print(corrected_customers[['CustomerID', 'MonthlyCharges']])
    
    # Export the cleaned data
    customer_info_db.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db.csv", index=False)
    print("\nCleaned data exported successfully!")
    
    # Show statistics after fix
    print("\n" + "="*50)
    print("MONTHLY CHARGES STATISTICS (AFTER FIX)")
    print("="*50)
    print(customer_info_db['MonthlyCharges'].describe())
else:
    print("\nNo negative monthly charges found.")
    print("\nMonthly charges statistics:")
    print(customer_info_db['MonthlyCharges'].describe())

Number of customers with negative monthly charges: 0

No negative monthly charges found.

Monthly charges statistics:
count    10000.000000
mean        51.003994
std         21.534495
min          0.380000
25%         39.797500
50%         50.015000
75%         60.500000
max        390.300000
Name: MonthlyCharges, dtype: float64

In [46]:
# Check for repeated customer IDs in customer_info_db dataset
customer_info_db = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db.csv")

# Check for duplicate CustomerIDs
duplicate_count = customer_info_db['CustomerID'].duplicated().sum()
print(f"Number of duplicate CustomerIDs: {duplicate_count}")

# Get unique count of CustomerIDs
unique_customers = customer_info_db['CustomerID'].nunique()
total_rows = len(customer_info_db)
print(f"Total rows: {total_rows}")
print(f"Unique customer IDs: {unique_customers}")

# If duplicates exist, show them
if duplicate_count > 0:
    print("\n" + "="*50)
    print("DUPLICATE CUSTOMER IDs FOUND")
    print("="*50)
    
    # Get all duplicate rows
    duplicates = customer_info_db[customer_info_db['CustomerID'].duplicated(keep=False)]
    print(f"\nAll rows with duplicate CustomerIDs ({len(duplicates)} rows):")
    print(duplicates.sort_values('CustomerID'))
    
    # Show which customer IDs are duplicated
    duplicated_ids = customer_info_db[customer_info_db['CustomerID'].duplicated()]['CustomerID'].unique()
    print(f"\nCustomer IDs that appear more than once ({len(duplicated_ids)} unique IDs):")
    for cust_id in duplicated_ids:
        count = customer_info_db[customer_info_db['CustomerID'] == cust_id].shape[0]
        print(f"  {cust_id}: {count} occurrences")
else:
    print("\nNo duplicate CustomerIDs found in the dataset.")

Number of duplicate CustomerIDs: 0
Total rows: 10000
Unique customer IDs: 10000

No duplicate CustomerIDs found in the dataset.

deleted the over occurenece of the customer ids of the newest signup date in the customer_info_db dataset manually

In [47]:
usage_data_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 120060 entries, 0 to 120059
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CustomerID   120060 non-null  str
 1   Month        120060 non-null  int64
 2   CallMinutes  120060 non-null  float64
 3   DataUsageGB  120060 non-null  float64
 4   SMSCount     120060 non-null  int64
 5   Complaints   120060 non-null  int64
dtypes: float64(2), int64(3), str(1)
memory usage: 6.5 MB

In [48]:
usage_data_db.describe()

,Month,CallMinutes,DataUsageGB,SMSCount,Complaints
count,120060.000000,120060.000000,120060.000000,120060.000000,120060.000000
mean,6.500000,492.422138,9.897935,24.525429,0.503023
std,3.452067,117.479898,3.067880,14.423950,0.708827
min,1.000000,34.140000,0.000000,0.000000,0.000000
25%,3.750000,418.450000,7.810000,12.000000,0.000000
50%,6.500000,494.995000,9.920000,25.000000,0.000000
75%,9.250000,571.120000,11.980000,37.000000,1.000000
max,12.000000,914.160000,22.730000,49.000000,6.000000

In [49]:
usage_data_db.duplicated().sum()

np.int64(60)

In [50]:
usage_data_db.drop_duplicates(inplace=True)

In [51]:
usage_data_db.duplicated().sum()

np.int64(0)

In [52]:
usage_data_db.info()

<class 'pandas.DataFrame'>
Index: 120000 entries, 0 to 120059
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CustomerID   120000 non-null  str
 1   Month        120000 non-null  int64
 2   CallMinutes  120000 non-null  float64
 3   DataUsageGB  120000 non-null  float64
 4   SMSCount     120000 non-null  int64
 5   Complaints   120000 non-null  int64
dtypes: float64(2), int64(3), str(1)
memory usage: 7.4 MB

In [53]:
usage_data_db.reset_index(drop=True, inplace=True)

In [54]:
usage_data_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CustomerID   120000 non-null  str
 1   Month        120000 non-null  int64
 2   CallMinutes  120000 non-null  float64
 3   DataUsageGB  120000 non-null  float64
 4   SMSCount     120000 non-null  int64
 5   Complaints   120000 non-null  int64
dtypes: float64(2), int64(3), str(1)
memory usage: 6.5 MB

In [55]:
usage_data_db.duplicated().sum()

np.int64(0)

In [56]:
merged_data2=pd.merge(customer_info_db,usage_data_db,on='CustomerID',how='left')
merged_data2=pd.merge(merged_data2,churn_labels_db,on='CustomerID',how='left')

In [57]:
merged_data2.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\merged_data2.csv", index=False)

In [58]:
merged_data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CustomerID      120000 non-null  str
 1   Age             120000 non-null  float64
 2   Gender          120000 non-null  str
 3   Region          120000 non-null  str
 4   ContractType    120000 non-null  str
 5   MonthlyCharges  120000 non-null  float64
 6   SignupDate      120000 non-null  str
 7   Month           120000 non-null  int64
 8   CallMinutes     120000 non-null  float64
 9   DataUsageGB     120000 non-null  float64
 10  SMSCount        120000 non-null  int64
 11  Complaints      120000 non-null  int64
 12  Churn           120000 non-null  int64
dtypes: float64(4), int64(4), str(5)
memory usage: 16.2 MB

In [59]:
merged_data2.describe()

,Age,MonthlyCharges,Month,CallMinutes,DataUsageGB,SMSCount,Complaints,Churn
count,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000
mean,43.364050,51.003994,6.500000,492.401958,9.898117,24.525392,0.503000,0.078600
std,12.096531,21.533508,3.452067,117.443986,3.067815,14.423944,0.708763,0.269115
min,18.000000,0.380000,1.000000,34.140000,0.000000,0.000000,0.000000,0.000000
25%,37.000000,39.797500,3.750000,418.450000,7.810000,12.000000,0.000000,0.000000
50%,43.000000,50.015000,6.500000,494.960000,9.920000,25.000000,0.000000,0.000000
75%,49.000000,60.500000,9.250000,571.080000,11.980000,37.000000,1.000000,0.000000
max,69.000000,390.300000,12.000000,914.160000,22.730000,49.000000,6.000000,1.000000

In [60]:
merged_data2.duplicated().sum()

np.int64(0)