# Telecom Customer Intelligence - Data Processing

This notebook processes raw telecom customer data for analysis and database loading.

## 1. Load Raw Data

Import and load the three raw datasets:
- customer_info.csv
- usage_data.csv
- churn_labels.csv

In [72]:
import pandas as pd
customer_info = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\raw\customer_info.csv")
usage_data = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\raw\usage_data.csv")
churn_labels = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\raw\churn_labels.csv")

In [73]:
customer_info

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate
0,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20
1,CUST_1,NaN,Female,Suburban,Prepaid,38.94,2020-01-25
2,CUST_2,46.0,Female,Rural,Monthly,48.56,2022-08-31
3,CUST_3,NaN,Female,Urban,Prepaid,24.22,2018-12-09
4,CUST_4,60.0,Male,Rural,Monthly,67.86,2022-12-28
...,...,...,...,...,...,...,...
10195,CUST_1134,NaN,Male,Suburban,Yearly,55.07,2019-02-18
10196,CUST_1306,NaN,Female,Urban,Monthly,66.51,2022-06-01
10197,CUST_6853,52.0,Female,Suburban,Yearly,55.03,2019-07-05
10198,CUST_1479,31.0,Female,Suburban,Monthly,58.80,2020-04-01
10199,CUST_4916,NaN,Female,Urban,Yearly,52.52,2022-08-17

In [74]:
usage_data

       CustomerID       Month  CallMinutes  DataUsageGB  SMSCount  Complaints
0          CUST_0  2023-01-31       518.12         7.21         9           1
1          CUST_0  2023-02-28       439.79         5.99        35           1
2          CUST_0  2023-03-31       545.06        14.16        14           1
3          CUST_0  2023-04-30       461.78         6.66        40           0
4          CUST_0  2023-05-31       434.82        12.75        26           2
...           ...         ...          ...          ...       ...         ...
119995  CUST_9999  2023-08-31       449.41         9.40        28           0
119996  CUST_9999  2023-09-30       599.84        11.51        34           2
119997  CUST_9999  2023-10-31       456.81         6.35        11           1
119998  CUST_9999  2023-11-30       466.54        13.47        39           1
119999  CUST_9999  2023-12-31       489.63        11.47         9           1

[120000 rows x 6 columns]

In [75]:
churn_labels

     CustomerID  Churn
0        CUST_0      0
1        CUST_1      0
2        CUST_2      0
3        CUST_3      0
4        CUST_4      0
...         ...    ...
9995  CUST_9995      0
9996  CUST_9996      1
9997  CUST_9997      0
9998  CUST_9998      0
9999  CUST_9999      0

[10000 rows x 2 columns]

In [76]:
customer_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      10200 non-null  str
 1   Age             6617 non-null   float64
 2   Gender          10200 non-null  str
 3   Region          10200 non-null  str
 4   ContractType    10200 non-null  str
 5   MonthlyCharges  10200 non-null  float64
 6   SignupDate      10200 non-null  str
dtypes: float64(2), str(5)
memory usage: 923.7 KB

In [77]:
customer_info["Age"].isnull().sum()

np.int64(3583)

In [78]:
customer_info.duplicated().sum()

np.int64(195)

In [79]:
customer_info.drop_duplicates()

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate
0,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20
1,CUST_1,NaN,Female,Suburban,Prepaid,38.94,2020-01-25
2,CUST_2,46.0,Female,Rural,Monthly,48.56,2022-08-31
3,CUST_3,NaN,Female,Urban,Prepaid,24.22,2018-12-09
4,CUST_4,60.0,Male,Rural,Monthly,67.86,2022-12-28
...,...,...,...,...,...,...,...
10024,CUST_248,22.0,Male,Rural,Monthly,58.85,2022-06-09
10076,CUST_466,23.0,Female,Urban,Monthly,45.18,2021-07-03
10089,CUST_333,NaN,Male,Rural,Prepaid,63.64,2023-02-11
10144,CUST_308,37.0,Male,Urban,Monthly,42.28,2018-03-01
10150,CUST_391,NaN,Female,Urban,Yearly,31.60,2023-03-11

In [80]:
customer_info["SignupDate"] = pd.to_datetime(customer_info["SignupDate"])

In [81]:
print(customer_info["SignupDate"].max())
print(customer_info["SignupDate"].min())

2023-11-03 00:00:00
2018-01-01 00:00:00

In [82]:
customer_info["SignupDate"].dt.year.max() - customer_info["SignupDate"].dt.year.min()

np.int32(5)

In [83]:
usage_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CustomerID   120000 non-null  str
 1   Month        120000 non-null  str
 2   CallMinutes  120000 non-null  float64
 3   DataUsageGB  120000 non-null  float64
 4   SMSCount     120000 non-null  int64
 5   Complaints   120000 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 7.7 MB

In [84]:
usage_data['Month'] = pd.to_datetime(usage_data['Month'])
usage_data['Month'] = usage_data['Month'].dt.month
# usage_data['Month'].values
# usage_data.head()
usage_data['Month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

## 2. Data Exploration & Cleaning

Explore the customer_info dataset:
- Check data types and missing values
- Check for duplicates
- Convert SignupDate to datetime

In [85]:
churn_labels.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  10000 non-null  str
 1   Churn       10000 non-null  int64
dtypes: int64(1), str(1)
memory usage: 243.2 KB

In [86]:
churn_labels.duplicated().sum()

np.int64(0)

In [87]:
# Merge all three tables on CustomerID
merged_data = pd.merge(customer_info, churn_labels, on='CustomerID', how='inner')
merged_data = pd.merge(merged_data, usage_data, on='CustomerID', how='inner')
# Sort ascending by CustomerID
merged_data = merged_data.sort_values('CustomerID')
merged_data

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate,Churn,Month,CallMinutes,DataUsageGB,SMSCount,Complaints
0,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,1,518.12,7.21,9,1
1,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,2,439.79,5.99,35,1
2,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,3,545.06,14.16,14,1
3,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,4,461.78,6.66,40,0
4,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,5,434.82,12.75,26,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,8,449.41,9.40,28,0
119996,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,9,599.84,11.51,34,2
119997,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,10,456.81,6.35,11,1
119998,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,11,466.54,13.47,39,1
119999,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,12,489.63,11.47,9,1

In [88]:
merged_data.duplicated().sum()

np.int64(2340)

In [89]:
merged_data.drop_duplicates(inplace=True)

In [90]:
merged_data

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate,Churn,Month,CallMinutes,DataUsageGB,SMSCount,Complaints
0,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,1,518.12,7.21,9,1
1,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,2,439.79,5.99,35,1
2,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,3,545.06,14.16,14,1
3,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,4,461.78,6.66,40,0
4,CUST_0,NaN,Male,Urban,Yearly,48.18,2021-03-20,0,5,434.82,12.75,26,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,8,449.41,9.40,28,0
119996,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,9,599.84,11.51,34,2
119997,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,10,456.81,6.35,11,1
119998,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,11,466.54,13.47,39,1
119999,CUST_9999,32.0,Female,Suburban,Monthly,9.22,2019-04-15,0,12,489.63,11.47,9,1

In [91]:
print(merged_data['Month'].value_counts())
print("\n")
print(merged_data['Month'].unique())

Month
1     10005
2     10005
3     10005
4     10005
5     10005
6     10005
7     10005
8     10005
9     10005
10    10005
11    10005
12    10005
Name: count, dtype: int64


[ 1  2  3  4  5  6  7  8  9 10 11 12]

## 3. Usage Data Processing

Process the usage_data dataset:
- Check data structure
- Convert Month to numeric format

In [92]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 120060 entries, 0 to 119999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CustomerID      120060 non-null  str
 1   Age             78036 non-null   float64
 2   Gender          120060 non-null  str
 3   Region          120060 non-null  str
 4   ContractType    120060 non-null  str
 5   MonthlyCharges  120060 non-null  float64
 6   SignupDate      120060 non-null  datetime64[us]
 7   Churn           120060 non-null  int64
 8   Month           120060 non-null  int32
 9   CallMinutes     120060 non-null  float64
 10  DataUsageGB     120060 non-null  float64
 11  SMSCount        120060 non-null  int64
 12  Complaints      120060 non-null  int64
dtypes: datetime64[us](1), float64(4), int32(1), int64(3), str(4)
memory usage: 15.5 MB

In [93]:
merged_data['Churn'].value_counts()

Churn
0    110616
1      9444
Name: count, dtype: int64

## 4. Churn Labels Processing

Check the churn_labels dataset:
- Verify data structure
- Check for duplicates

In [94]:
# Correlation matrix between Age and other numeric features
numeric_cols = merged_data.select_dtypes(include=['number']).columns
correlation_matrix = merged_data[numeric_cols].corr()
# Focus on Age correlations
age_correlation = correlation_matrix[['Age']].sort_values('Age', ascending=False)
age_correlation

                         Age
Age             1.000000e+00
CallMinutes     1.721142e-02
Churn           7.783950e-03
DataUsageGB     1.851191e-03
SMSCount        1.798290e-03
Month          -2.428390e-18
Complaints     -2.452721e-03
MonthlyCharges -1.409156e-02

## 5. Merge Datasets

Merge all three datasets on CustomerID:
- Inner join customer_info with churn_labels
- Merge with usage_data
- Sort by CustomerID
- Remove duplicates

In [95]:
merged_data.groupby('ContractType')['Age'].median()

ContractType
Monthly    43.0
Prepaid    44.0
Yearly     43.0
Name: Age, dtype: float64

In [96]:
merged_data.groupby('Gender')['Age'].median()

Gender
Female    43.0
Male      44.0
Name: Age, dtype: float64

In [97]:
merged_data.groupby('Region')['Age'].median()

Region
Rural       43.0
Suburban    44.0
Urban       42.0
Name: Age, dtype: float64

In [98]:
merged_data['Age'] = merged_data.groupby(
    ['Gender', 'Region', 'ContractType']
)['Age'].transform(lambda x: x.fillna(x.median()))

In [99]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 120060 entries, 0 to 119999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CustomerID      120060 non-null  str
 1   Age             120060 non-null  float64
 2   Gender          120060 non-null  str
 3   Region          120060 non-null  str
 4   ContractType    120060 non-null  str
 5   MonthlyCharges  120060 non-null  float64
 6   SignupDate      120060 non-null  datetime64[us]
 7   Churn           120060 non-null  int64
 8   Month           120060 non-null  int32
 9   CallMinutes     120060 non-null  float64
 10  DataUsageGB     120060 non-null  float64
 11  SMSCount        120060 non-null  int64
 12  Complaints      120060 non-null  int64
dtypes: datetime64[us](1), float64(4), int32(1), int64(3), str(4)
memory usage: 15.5 MB

## 6. Data Analysis

Analyze the merged dataset:
- Check Churn distribution
- Analyze Age correlations
- Group by ContractType, Gender, Region

In [100]:
# Feature Engineering: Calculate Customer Tenure (in months)
merged_data['TenureMonths'] = (merged_data['SignupDate'].max() - merged_data['SignupDate']).dt.days // 30
merged_data.head()

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate,Churn,Month,CallMinutes,DataUsageGB,SMSCount,Complaints,TenureMonths
0,CUST_0,42.0,Male,Urban,Yearly,48.18,2021-03-20,0,1,518.12,7.21,9,1,31
1,CUST_0,42.0,Male,Urban,Yearly,48.18,2021-03-20,0,2,439.79,5.99,35,1,31
2,CUST_0,42.0,Male,Urban,Yearly,48.18,2021-03-20,0,3,545.06,14.16,14,1,31
3,CUST_0,42.0,Male,Urban,Yearly,48.18,2021-03-20,0,4,461.78,6.66,40,0,31
4,CUST_0,42.0,Male,Urban,Yearly,48.18,2021-03-20,0,5,434.82,12.75,26,2,31

In [101]:
merged_data['SignupDate'].max()

Timestamp('2023-11-03 00:00:00')

In [102]:
# Display rows with TenureMonths = 0
zero_tenure = merged_data[merged_data['TenureMonths'] == 0]
print(f"Number of rows with TenureMonths = 0: {len(zero_tenure)}")
zero_tenure.head()

Number of rows with TenureMonths = 0: 36

,CustomerID,Age,Gender,Region,ContractType,MonthlyCharges,SignupDate,Churn,Month,CallMinutes,DataUsageGB,SMSCount,Complaints,TenureMonths
2184,CUST_182,45.0,Female,Rural,Monthly,52.69,2023-11-03,1,1,436.15,9.19,2,0,0
2185,CUST_182,45.0,Female,Rural,Monthly,52.69,2023-11-03,1,2,291.19,9.66,23,0,0
2186,CUST_182,45.0,Female,Rural,Monthly,52.69,2023-11-03,1,3,389.08,10.85,26,0,0
2187,CUST_182,45.0,Female,Rural,Monthly,52.69,2023-11-03,1,4,380.66,7.97,28,1,0
2188,CUST_182,45.0,Female,Rural,Monthly,52.69,2023-11-03,1,5,313.68,4.62,46,0,0

In [103]:
# Check Churn class balance
churn_counts = merged_data['Churn'].value_counts()
churn_percentage = merged_data['Churn'].value_counts(normalize=True) * 100
print("Churn Counts:")
print(churn_counts)
print("\nChurn Percentage:")
print(churn_percentage)

Churn Counts:
Churn
0    110616
1      9444
Name: count, dtype: int64

Churn Percentage:
Churn
0    92.133933
1     7.866067
Name: proportion, dtype: float64

## 7. Handle Missing Values

Fill missing Age values using median based on:
- Gender
- Region
- ContractType

In [104]:
numeric_cols = ['Age', 'MonthlyCharges', 'CallMinutes', 'DataUsageGB', 'SMSCount', 'Complaints', 'TenureMonths']
outlier_summary = {}

for col in numeric_cols:
    Q1 = merged_data[col].quantile(0.25)
    Q3 = merged_data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = merged_data[(merged_data[col] < lower_bound) | (merged_data[col] > upper_bound)][col].count()
    outlier_summary[col] = outliers

print("Outlier counts per column:")
for col, count in outlier_summary.items():
    print(f"{col}: {count} outliers ({count/len(merged_data)*100:.2f}%)")

Outlier counts per column:
Age: 4500 outliers (3.75%)
MonthlyCharges: 1332 outliers (1.11%)
CallMinutes: 1611 outliers (1.34%)
DataUsageGB: 681 outliers (0.57%)
SMSCount: 0 outliers (0.00%)
Complaints: 1748 outliers (1.46%)
TenureMonths: 0 outliers (0.00%)

## 8. Feature Engineering

Create new features:
- TenureMonths: Calculate customer tenure in months from SignupDate

In [105]:
# Split merged data back into original 3 tables for database
customer_data_processed = pd.read_csv('D:/Ahmed/My Projects/telecom intelligence project/data/processed/customer_data_processed.csv')
# Extract customer_info (unique customers only)
customer_info_db = customer_data_processed[['CustomerID', 'Age', 'Gender', 'Region', 'ContractType', 'MonthlyCharges', 'SignupDate']].drop_duplicates()
customer_info_db = customer_info_db.reset_index(drop=True)

# Extract usage_data
usage_data_db = customer_data_processed[['CustomerID', 'Month', 'CallMinutes', 'DataUsageGB', 'SMSCount', 'Complaints']].drop_duplicates()
usage_data_db = usage_data_db.reset_index(drop=True)

# Extract churn_labels (unique customers only)
churn_labels_db = customer_data_processed[['CustomerID', 'Churn']].drop_duplicates()
churn_labels_db = churn_labels_db.reset_index(drop=True)

print("customer_info_db shape:", customer_info_db.shape)
print("usage_data_db shape:", usage_data_db.shape)
print("churn_labels_db shape:", churn_labels_db.shape)

customer_info_db shape: (10005, 7)
usage_data_db shape: (120000, 6)
churn_labels_db shape: (10000, 2)

## 9. Churn Analysis

Analyze churn patterns:
- Check churn class balance
- Calculate churn counts and percentages

In [106]:
customer_data_processed = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_data_processed.csv")
customer_data_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 120060 entries, 0 to 120059
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CustomerID      120060 non-null  str
 1   Age             120060 non-null  float64
 2   Gender          120060 non-null  str
 3   Region          120060 non-null  str
 4   ContractType    120060 non-null  str
 5   MonthlyCharges  120060 non-null  float64
 6   SignupDate      120060 non-null  str
 7   Churn           120060 non-null  int64
 8   Month           120060 non-null  int64
 9   CallMinutes     120060 non-null  float64
 10  DataUsageGB     120060 non-null  float64
 11  SMSCount        120060 non-null  int64
 12  Complaints      120060 non-null  int64
 13  TenureMonths    120060 non-null  int64
dtypes: float64(4), int64(5), str(5)
memory usage: 17.0 MB

## 10. Outlier Detection

Detect outliers in numeric columns using IQR method:
- Age
- MonthlyCharges
- CallMinutes
- DataUsageGB
- SMSCount
- Complaints
- TenureMonths

In [107]:
# Split merged data back into original 3 tables for database
# Extract customer_info (unique customers only)
customer_info_db = customer_data_processed[['CustomerID', 'Age', 'Gender', 'Region', 'ContractType', 'MonthlyCharges', 'SignupDate']].drop_duplicates()
customer_info_db = customer_info_db.reset_index(drop=True)

# Extract usage_data
usage_data_db = customer_data_processed[['CustomerID', 'Month', 'CallMinutes', 'DataUsageGB', 'SMSCount', 'Complaints']]

# Extract churn_labels (unique customers only)
churn_labels_db = customer_data_processed[['CustomerID', 'Churn']].drop_duplicates()
churn_labels_db = churn_labels_db.reset_index(drop=True)

print("customer_info_db shape:", customer_info_db.shape)
print("usage_data_db shape:", usage_data_db.shape)
print("churn_labels_db shape:", churn_labels_db.shape)

customer_info_db shape: (10005, 7)
usage_data_db shape: (120060, 6)
churn_labels_db shape: (10000, 2)

## 11. Split Data for Database

Split the merged data back into three separate tables for database loading:
- customer_info_db (unique customers only)
- usage_data_db (monthly usage records)
- churn_labels_db (unique customers only)

In [108]:
# Export the three tables for database loading
customer_info_db.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db.csv", index=False)
usage_data_db.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\usage_data_db.csv", index=False)
churn_labels_db.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\churn_labels_db.csv", index=False)
print("All three tables exported successfully!")

All three tables exported successfully!

In [109]:
usage_data_db["CustomerID"].nunique()

10000

In [110]:
usage_data_db.duplicated().sum()

np.int64(60)

In [111]:
usage_data_db.drop_duplicates(inplace=True)

In [112]:
usage_data_db.reset_index(drop=True)

       CustomerID  Month  CallMinutes  DataUsageGB  SMSCount  Complaints
0          CUST_0      1       518.12         7.21         9           1
1          CUST_0      2       439.79         5.99        35           1
2          CUST_0      3       545.06        14.16        14           1
3          CUST_0      4       461.78         6.66        40           0
4          CUST_0      5       434.82        12.75        26           2
...           ...    ...          ...          ...       ...         ...
119995  CUST_9999      8       449.41         9.40        28           0
119996  CUST_9999      9       599.84        11.51        34           2
119997  CUST_9999     10       456.81         6.35        11           1
119998  CUST_9999     11       466.54        13.47        39           1
119999  CUST_9999     12       489.63        11.47         9           1

[120000 rows x 6 columns]

In [113]:
usage_data_db.duplicated().sum()

np.int64(0)

In [114]:
usage_data_db.isnull().sum()

CustomerID     0
Month          0
CallMinutes    0
DataUsageGB    0
SMSCount       0
Complaints     0
dtype: int64

In [115]:
usage_data_db.info()

<class 'pandas.DataFrame'>
Index: 120000 entries, 0 to 120059
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CustomerID   120000 non-null  str
 1   Month        120000 non-null  int64
 2   CallMinutes  120000 non-null  float64
 3   DataUsageGB  120000 non-null  float64
 4   SMSCount     120000 non-null  int64
 5   Complaints   120000 non-null  int64
dtypes: float64(2), int64(3), str(1)
memory usage: 7.4 MB

In [116]:
customer_info_db.duplicated().sum()

np.int64(0)

In [117]:
customer_info_db.isnull().sum()

CustomerID        0
Age               0
Gender            0
Region            0
ContractType      0
MonthlyCharges    0
SignupDate        0
dtype: int64

In [118]:
churn_labels_db.duplicated().sum()

np.int64(0)

In [119]:
churn_labels_db.isnull().sum()

CustomerID    0
Churn         0
dtype: int64

In [120]:
usage_data_db.duplicated().sum()

np.int64(0)

In [ ]:
# Check for repeated customer IDs in customer_info_db dataset
customer_info_db = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db.csv")

# Check for duplicate CustomerIDs
duplicate_count = customer_info_db['CustomerID'].duplicated().sum()
print(f"Number of duplicate CustomerIDs: {duplicate_count}")

# Get unique count of CustomerIDs
unique_customers = customer_info_db['CustomerID'].nunique()
total_rows = len(customer_info_db)
print(f"Total rows: {total_rows}")
print(f"Unique customer IDs: {unique_customers}")

# If duplicates exist, show them
if duplicate_count > 0:
    print("\n" + "="*50)
    print("DUPLICATE CUSTOMER IDs FOUND")
    print("="*50)
    
    # Get all duplicate rows
    duplicates = customer_info_db[customer_info_db['CustomerID'].duplicated(keep=False)]
    print(f"\nAll rows with duplicate CustomerIDs ({len(duplicates)} rows):")
    print(duplicates.sort_values('CustomerID'))
    
    # Show which customer IDs are duplicated
    duplicated_ids = customer_info_db[customer_info_db['CustomerID'].duplicated()]['CustomerID'].unique()
    print(f"\nCustomer IDs that appear more than once ({len(duplicated_ids)} unique IDs):")
    for cust_id in duplicated_ids:
        count = customer_info_db[customer_info_db['CustomerID'] == cust_id].shape[0]
        print(f"  {cust_id}: {count} occurrences")
else:
    print("\nNo duplicate CustomerIDs found in the dataset.")

KeyError: 'CustomerID'

In [14]:
# Check for negative monthly charges
import pandas as pd
customer_info_db2 = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db2.csv")

# Check for negative values in monthly_charges
negative_charges = customer_info_db2[customer_info_db2['monthly_charges'] < 0]
print(f"Number of customers with negative monthly charges: {len(negative_charges)}")

if len(negative_charges) > 0:
    print("\n" + "="*50)
    print("CUSTOMERS WITH NEGATIVE MONTHLY CHARGES")
    print("="*50)
    print(negative_charges)
    
    # Get statistics on monthly charges
    print("\n" + "="*50)
    print("MONTHLY CHARGES STATISTICS (BEFORE FIX)")
    print("="*50)
    print(customer_info_db2['monthly_charges'].describe())
    
    # Fix negative values by converting to positive (sign error correction)
    print("\n" + "="*50)
    print("FIXING NEGATIVE VALUES")
    print("="*50)
    customer_info_db2['monthly_charges'] = customer_info_db2['monthly_charges'].abs()
    
    # Verify fix
    negative_after = customer_info_db2[customer_info_db2['monthly_charges'] < 0]
    print(f"Negative values after fix: {len(negative_after)}")
    
    # Show the corrected records
    corrected_customers = customer_info_db2[customer_info_db2['customer_id'].isin(negative_charges['customer_id'])]
    print("\nCorrected records:")
    print(corrected_customers[['customer_id', 'monthly_charges']])
    
    # Export the cleaned data
    customer_info_db2.to_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\customer_info_db2.csv", index=False)
    print("\nCleaned data exported successfully!")
    
    # Show statistics after fix
    print("\n" + "="*50)
    print("MONTHLY CHARGES STATISTICS (AFTER FIX)")
    print("="*50)
    print(customer_info_db2['monthly_charges'].describe())
else:
    print("\nNo negative monthly charges found.")
    print("\nMonthly charges statistics:")
    print(customer_info_db2['monthly_charges'].describe())

Number of customers with negative monthly charges: 5

==================================================
CUSTOMERS WITH NEGATIVE MONTHLY CHARGES
==================================================
     customer_id   age  gender    region contract_type  monthly_charges  \
4081   CUST_4671  56.0    Male     Rural       Prepaid            -3.89
5085   CUST_5575  39.0  Female  Suburban       Monthly            -0.46
6469   CUST_6820  60.0    Male     Urban        Yearly            -3.15
8409   CUST_8567  36.0    Male     Rural       Prepaid            -6.72
9339   CUST_9403  19.0    Male     Rural       Monthly            -4.55

     signup_date
4081  2020-11-12
5085  2023-02-01
6469  2018-02-09
8409  2018-04-17
9339  2023-05-18

==================================================
MONTHLY CHARGES STATISTICS (BEFORE FIX)
==================================================
count    10000.000000
mean        51.000240
std         21.543385
min         -6.720000
25%         39.797500
50%         50.015000
75%         60.500000
max        390.300000
Name: monthly_charges, dtype: float64

==================================================
FIXING NEGATIVE VALUES
==================================================
Negative values after fix: 0

Corrected records:
     customer_id  monthly_charges
4081   CUST_4671             3.89
5085   CUST_5575             0.46
6469   CUST_6820             3.15
8409   CUST_8567             6.72
9339   CUST_9403             4.55

Cleaned data exported successfully!

==================================================
MONTHLY CHARGES STATISTICS (AFTER FIX)
==================================================
count    10000.000000
mean        51.003994
std         21.534495
min          0.380000
25%         39.797500
50%         50.015000
75%         60.500000
max        390.300000
Name: monthly_charges, dtype: float64

In [6]:
usage_data_db2 = pd.read_csv(r"D:\Ahmed\My Projects\telecom intelligence project\data\processed\usage_data_db2.csv")
usage_data_db2.describe()

,Month,CallMinutes,DataUsageGB,SMSCount,Complaints
count,120060.000000,120060.000000,120060.000000,120060.000000,120060.000000
mean,6.500000,492.422138,9.897935,24.525429,0.503023
std,3.452067,117.479898,3.067880,14.423950,0.708827
min,1.000000,34.140000,0.000000,0.000000,0.000000
25%,3.750000,418.450000,7.810000,12.000000,0.000000
50%,6.500000,494.995000,9.920000,25.000000,0.000000
75%,9.250000,571.120000,11.980000,37.000000,1.000000
max,12.000000,914.160000,22.730000,49.000000,6.000000

## 12. Export Processed Data

Export the three tables to CSV files for database loading.

## 13. Data Validation

Validate the exported datasets:
- Check for duplicates
- Check for null values
- Verify data integrity

## 14. Data Quality Checks

Additional quality checks:
- Check for duplicate CustomerIDs in customer_info_db
- Fix negative monthly charges (sign errors)